---
- hosts: all
  vars:
    directories:
      - { path: "/opt/project1", mode: "0755" }
      - { path: "/opt/project2", mode: "0700" }
      - { path: "/opt/project3", mode: "0777" }

  tasks:
    - name: Create Project directory if directories dont't exists
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        mode: "{{ item.mode }}"
      loop:
        "{{ directories }}"
      register: result

    - name: Print result
      ansible.builtin.debug:
        msg: "Directory {{ item.item.path }} (mode={{ item.item.mode}}) -> changed={{ item.changed }}"
      loop:
        "{{ result.results }}"