---
- hosts: all
  vars:
    users:
      - userA
      - userB
      - userC
  tasks:
    - name: Create users with bash shell
      ansible.builtin.user:
        name: "{{ item }}"
        shell: /bin/bash
        create_home: true
      loop:
        "{{ users }}"
      register: result

    - name: Print result
      ansible.builtin.debug:
        msg: "User {{ item.item }} create => changed {{ item.changed }}"
      loop:
        "{{ result.results }}"